### ISSUE TITLE
Create all the pages required for normal user with layout but no content.

### ISSUE THREAD

**Issue by Robin-Kurian** [Evrz-Developers/babyparadisedeals#14]
### Tasks
- [x] Login page 
- [x] Register page
- [x] User Profile page
- [x] Product page
- [x] Product detail page
- [x] Cart page
- [x] Checkout page
- [x] Orders page
- [x] About us with location
